"""Shared fixtures for the relational-transformer test suite.

These tests exercise the *installed wheel* (the public `rt` API + the compiled
`rt._rustler` engine), so run them against a built + installed package -- e.g.
`local/test.sh`, or the CI `test` job. torch/pyarrow-dependent tests skip
cleanly when those aren't present.
"""

from __future__ import annotations

import json

import pytest

TINY_DIMS = dict(num_blocks=2, d_model=16, d_text=8, num_heads=2, d_ff=32)


@pytest.fixture(scope="session")
def tiny_dims() -> dict:
    return dict(TINY_DIMS)


@pytest.fixture()
def tiny_checkpoint(tmp_path, tiny_dims):
    """A real checkpoint dir (config.json + model.safetensors) for a tiny model.

    Returns ``(checkpoint_dir, source_model)``.
    """
    pytest.importorskip("torch")
    from rt import RelationalTransformer
    from rt.checkpoints import CONFIG_FILE, MODEL_FILE, save_model

    src = RelationalTransformer(
        **tiny_dims, compile=False, materialize_attn_masks=True
    )
    ckpt = tmp_path / "ckpt"
    ckpt.mkdir()
    save_model(src.state_dict(), ckpt / MODEL_FILE)
    (ckpt / CONFIG_FILE).write_text(
        json.dumps({"model": tiny_dims, "embedding_model": "test-embed"})
    )
    return ckpt, src


@pytest.fixture()
def synthetic_dataset(tmp_path):
    """A small synthetic relbench-layout dataset generated by PluRel
    (manifest.yaml + db/<table>.parquet), for the preprocess round-trip."""
    import yaml

    pytest.importorskip("pyarrow")  # pandas .to_parquet backend
    plurel = pytest.importorskip("plurel")
    from plurel.config import Choices, DatabaseParams

    cfg = plurel.Config(
        database_params=DatabaseParams(
            num_tables_choices=Choices(kind="range", value=[2, 3]),
            num_rows_entity_table_choices=Choices(kind="range", value=[8, 12]),
            num_rows_activity_table_choices=Choices(kind="range", value=[15, 20]),
            num_cols_choices=Choices(kind="range", value=[3, 4]),
        )
    )
    db = plurel.SyntheticDataset(seed=0, config=cfg).make_db()

    ds = tmp_path / "synth"
    (ds / "db").mkdir(parents=True)
    tables = {}
    for name, table in db.table_dict.items():
        table.df.to_parquet(ds / "db" / f"{name}.parquet")
        spec = {}
        if table.pkey_col:
            spec["pkey"] = table.pkey_col
        if table.time_col:
            spec["time_col"] = table.time_col
        if table.fkey_col_to_pkey_table:
            spec["fkeys"] = dict(table.fkey_col_to_pkey_table)
        tables[name] = spec
    (ds / "manifest.yaml").write_text(yaml.safe_dump({"name": "synth", "tables": tables}))
    return ds
